// Generated by rstantools.  Do not edit by hand.

/*
    mxd is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    mxd is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with mxd.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_hb_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 61> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 20, column 2 to column 17)",
  " (in 'string', line 21, column 2 to column 17)",
  " (in 'string', line 22, column 2 to column 34)",
  " (in 'string', line 23, column 2 to column 27)",
  " (in 'string', line 26, column 2 to column 28)",
  " (in 'string', line 27, column 2 to column 19)",
  " (in 'string', line 28, column 2 to column 24)",
  " (in 'string', line 45, column 2 to column 21)",
  " (in 'string', line 46, column 2 to column 24)",
  " (in 'string', line 29, column 2 to column 57)",
  " (in 'string', line 30, column 2 to column 43)",
  " (in 'string', line 32, column 4 to column 115)",
  " (in 'string', line 31, column 17 to line 33, column 3)",
  " (in 'string', line 31, column 2 to line 33, column 3)",
  " (in 'string', line 47, column 2 to column 64)",
  " (in 'string', line 48, column 2 to column 53)",
  " (in 'string', line 37, column 2 to column 45)",
  " (in 'string', line 38, column 2 to column 58)",
  " (in 'string', line 39, column 2 to column 51)",
  " (in 'string', line 40, column 2 to column 98)",
  " (in 'string', line 42, column 2 to column 20)",
  " (in 'string', line 2, column 2 to column 17)",
  " (in 'string', line 3, column 2 to column 17)",
  " (in 'string', line 4, column 2 to column 17)",
  " (in 'string', line 5, column 2 to column 17)",
  " (in 'string', line 6, column 2 to column 17)",
  " (in 'string', line 7, column 20 to column 21)",
  " (in 'string', line 7, column 2 to column 23)",
  " (in 'string', line 8, column 19 to column 20)",
  " (in 'string', line 8, column 2 to column 22)",
  " (in 'string', line 9, column 9 to column 10)",
  " (in 'string', line 9, column 12 to column 13)",
  " (in 'string', line 9, column 2 to column 17)",
  " (in 'string', line 10, column 17 to column 18)",
  " (in 'string', line 10, column 2 to column 20)",
  " (in 'string', line 11, column 23 to column 24)",
  " (in 'string', line 11, column 2 to column 26)",
  " (in 'string', line 12, column 21 to column 22)",
  " (in 'string', line 12, column 2 to column 24)",
  " (in 'string', line 13, column 27 to column 28)",
  " (in 'string', line 13, column 2 to column 30)",
  " (in 'string', line 14, column 18 to column 19)",
  " (in 'string', line 14, column 2 to column 29)",
  " (in 'string', line 15, column 2 to column 28)",
  " (in 'string', line 16, column 2 to column 24)",
  " (in 'string', line 17, column 2 to column 28)",
  " (in 'string', line 20, column 9 to column 10)",
  " (in 'string', line 20, column 12 to column 13)",
  " (in 'string', line 21, column 9 to column 10)",
  " (in 'string', line 21, column 12 to column 13)",
  " (in 'string', line 22, column 23 to column 24)",
  " (in 'string', line 23, column 18 to column 19)",
  " (in 'string', line 27, column 9 to column 10)",
  " (in 'string', line 27, column 12 to column 13)",
  " (in 'string', line 28, column 9 to column 10)",
  " (in 'string', line 28, column 12 to column 17)",
  " (in 'string', line 45, column 9 to column 10)",
  " (in 'string', line 45, column 12 to column 13)",
  " (in 'string', line 46, column 9 to column 10)",
  " (in 'string', line 46, column 12 to column 17)"};
#include <stan_meta_header.hpp>
class model_hb final : public model_base_crtp<model_hb> {
private:
  int N;
  int I;
  int M;
  int K;
  int D;
  std::vector<int> item;
  std::vector<int> bw;
  Eigen::Matrix<double,-1,-1> Z_data__;
  std::vector<int> y;
  std::vector<int> start_n;
  std::vector<int> end_n;
  std::vector<int> id;
  Eigen::Matrix<double,-1,1> orig_id_data__;
  double prior_omega;
  double prior_b;
  double prior_sigma;
  int raw0_2dim__;
  int beta_2dim__;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> Z{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double,-1,1>> orig_id{nullptr, 0};
public:
  ~model_hb() {}
  model_hb(stan::io::var_context& context__, unsigned int random_seed__ = 0,
           std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ = "model_hb_namespace::model_hb";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 22;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 22;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 22;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 23;
      context__.validate_dims("data initialization", "I", "int",
        std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      current_statement__ = 23;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 23;
      stan::math::check_greater_or_equal(function__, "I", I, 1);
      current_statement__ = 24;
      context__.validate_dims("data initialization", "M", "int",
        std::vector<size_t>{});
      M = std::numeric_limits<int>::min();
      current_statement__ = 24;
      M = context__.vals_i("M")[(1 - 1)];
      current_statement__ = 24;
      stan::math::check_greater_or_equal(function__, "M", M, 1);
      current_statement__ = 25;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 25;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 25;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 26;
      context__.validate_dims("data initialization", "D", "int",
        std::vector<size_t>{});
      D = std::numeric_limits<int>::min();
      current_statement__ = 26;
      D = context__.vals_i("D")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "D", D, 1);
      current_statement__ = 27;
      stan::math::validate_non_negative_index("item", "M", M);
      current_statement__ = 28;
      context__.validate_dims("data initialization", "item", "int",
        std::vector<size_t>{static_cast<size_t>(M)});
      item = std::vector<int>(M, std::numeric_limits<int>::min());
      current_statement__ = 28;
      item = context__.vals_i("item");
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "item", item, 1);
      current_statement__ = 29;
      stan::math::validate_non_negative_index("bw", "M", M);
      current_statement__ = 30;
      context__.validate_dims("data initialization", "bw", "int",
        std::vector<size_t>{static_cast<size_t>(M)});
      bw = std::vector<int>(M, std::numeric_limits<int>::min());
      current_statement__ = 30;
      bw = context__.vals_i("bw");
      current_statement__ = 30;
      stan::math::check_greater_or_equal(function__, "bw", bw, -1);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("Z", "I", I);
      current_statement__ = 32;
      stan::math::validate_non_negative_index("Z", "D", D);
      current_statement__ = 33;
      context__.validate_dims("data initialization", "Z", "double",
        std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(D)});
      Z_data__ = Eigen::Matrix<double,-1,-1>::Constant(I, D,
                   std::numeric_limits<double>::quiet_NaN());
      new (&Z) Eigen::Map<Eigen::Matrix<double,-1,-1>>(Z_data__.data(), I, D);
      {
        std::vector<local_scalar_t__> Z_flat__;
        current_statement__ = 33;
        Z_flat__ = context__.vals_r("Z");
        current_statement__ = 33;
        pos__ = 1;
        current_statement__ = 33;
        for (int sym1__ = 1; sym1__ <= D; ++sym1__) {
          current_statement__ = 33;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 33;
            stan::model::assign(Z, Z_flat__[(pos__ - 1)],
              "assigning variable Z", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 33;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 34;
      stan::math::validate_non_negative_index("y", "N", N);
      current_statement__ = 35;
      context__.validate_dims("data initialization", "y", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      y = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 35;
      y = context__.vals_i("y");
      current_statement__ = 35;
      stan::math::check_greater_or_equal(function__, "y", y, 1);
      current_statement__ = 36;
      stan::math::validate_non_negative_index("start_n", "N", N);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "start_n", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      start_n = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 37;
      start_n = context__.vals_i("start_n");
      current_statement__ = 37;
      stan::math::check_greater_or_equal(function__, "start_n", start_n, 1);
      current_statement__ = 38;
      stan::math::validate_non_negative_index("end_n", "N", N);
      current_statement__ = 39;
      context__.validate_dims("data initialization", "end_n", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      end_n = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 39;
      end_n = context__.vals_i("end_n");
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "end_n", end_n, 1);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("id", "N", N);
      current_statement__ = 41;
      context__.validate_dims("data initialization", "id", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      id = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 41;
      id = context__.vals_i("id");
      current_statement__ = 41;
      stan::math::check_greater_or_equal(function__, "id", id, 1);
      current_statement__ = 41;
      stan::math::check_less_or_equal(function__, "id", id, I);
      current_statement__ = 42;
      stan::math::validate_non_negative_index("orig_id", "I", I);
      current_statement__ = 43;
      context__.validate_dims("data initialization", "orig_id", "double",
        std::vector<size_t>{static_cast<size_t>(I)});
      orig_id_data__ = Eigen::Matrix<double,-1,1>::Constant(I,
                         std::numeric_limits<double>::quiet_NaN());
      new (&orig_id)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(orig_id_data__.data(), I);
      {
        std::vector<local_scalar_t__> orig_id_flat__;
        current_statement__ = 43;
        orig_id_flat__ = context__.vals_r("orig_id");
        current_statement__ = 43;
        pos__ = 1;
        current_statement__ = 43;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 43;
          stan::model::assign(orig_id, orig_id_flat__[(pos__ - 1)],
            "assigning variable orig_id", stan::model::index_uni(sym1__));
          current_statement__ = 43;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "orig_id", orig_id, 1);
      current_statement__ = 44;
      context__.validate_dims("data initialization", "prior_omega", "double",
        std::vector<size_t>{});
      prior_omega = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 44;
      prior_omega = context__.vals_r("prior_omega")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "prior_omega",
        prior_omega, 0);
      current_statement__ = 45;
      context__.validate_dims("data initialization", "prior_b", "double",
        std::vector<size_t>{});
      prior_b = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 45;
      prior_b = context__.vals_r("prior_b")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "prior_b", prior_b, 0);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "prior_sigma", "double",
        std::vector<size_t>{});
      prior_sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 46;
      prior_sigma = context__.vals_r("prior_sigma")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "prior_sigma",
        prior_sigma, 0);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("z", "I", I);
      current_statement__ = 48;
      stan::math::validate_non_negative_index("z", "K", K);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("b", "D", D);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("b", "K", K);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("L_Omega", "K", K);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("L_Omega", "K", K);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("sigma", "K", K);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("raw", "I", I);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("raw", "K", K);
      current_statement__ = 55;
      stan::math::validate_non_negative_index("raw0", "I", I);
      current_statement__ = 56;
      raw0_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 56;
      raw0_2dim__ = (K + 1);
      current_statement__ = 56;
      stan::math::validate_non_negative_index("raw0", "K + 1", raw0_2dim__);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("Omega", "K", K);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("Omega", "K", K);
      current_statement__ = 59;
      stan::math::validate_non_negative_index("beta", "I", I);
      current_statement__ = 60;
      beta_2dim__ = std::numeric_limits<int>::min();
      current_statement__ = 60;
      beta_2dim__ = (K + 2);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("beta", "K + 2", beta_2dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (I * K) + (D * K) + ((K * (K - 1)) / 2) + K;
  }
  inline std::string model_name() const final {
    return "model_hb";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_hb_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,-1> z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(I, K, DUMMY_VAR__);
      current_statement__ = 1;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(I, K);
      Eigen::Matrix<local_scalar_t__,-1,-1> b =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, K, DUMMY_VAR__);
      current_statement__ = 2;
      b = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(D, K);
      Eigen::Matrix<local_scalar_t__,-1,-1> L_Omega =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, K, DUMMY_VAR__);
      current_statement__ = 3;
      L_Omega = in__.template read_constrain_cholesky_factor_corr<
                  Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, K);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      local_scalar_t__ log_lik = DUMMY_VAR__;
      current_statement__ = 5;
      log_lik = 0;
      Eigen::Matrix<local_scalar_t__,-1,-1> raw =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(I, K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,-1> raw0 =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(I, raw0_2dim__,
          DUMMY_VAR__);
      current_statement__ = 10;
      stan::model::assign(raw,
        stan::math::add(stan::math::multiply(Z, b),
          stan::math::multiply(z,
            stan::math::transpose(
              stan::math::diag_pre_multiply(sigma, L_Omega)))),
        "assigning variable raw");
      current_statement__ = 11;
      stan::model::assign(raw0,
        stan::math::append_col(raw, stan::math::rep_vector(0, I)),
        "assigning variable raw0");
      current_statement__ = 14;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 12;
        log_lik = (log_lik +
          ((stan::model::rvalue(bw, "bw",
              stan::model::index_uni(
                stan::model::rvalue(y, "y", stan::model::index_uni(n))))
          *
          stan::model::rvalue(raw0, "raw0",
            stan::model::index_uni(
              stan::model::rvalue(id, "id", stan::model::index_uni(n))),
            stan::model::index_uni(
              stan::model::rvalue(item, "item",
                stan::model::index_uni(
                  stan::model::rvalue(y, "y", stan::model::index_uni(n)))))))
          -
          stan::math::log_sum_exp(
            stan::math::multiply(
              stan::model::rvalue(bw, "bw",
                stan::model::index_uni(
                  stan::model::rvalue(y, "y", stan::model::index_uni(n)))),
              stan::model::rvalue(raw0, "raw0",
                stan::model::index_uni(
                  stan::model::rvalue(id, "id", stan::model::index_uni(n))),
                stan::model::index_multi(
                  stan::model::rvalue(item, "item",
                    stan::model::index_min_max(
                      stan::model::rvalue(start_n, "start_n",
                        stan::model::index_uni(n)),
                      stan::model::rvalue(end_n, "end_n",
                        stan::model::index_uni(n))))))))));
      }
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "log_lik", log_lik, 0);
      {
        current_statement__ = 17;
        lp_accum__.add(stan::math::normal_lpdf<false>(
                         stan::math::to_vector(z), 0, 1));
        current_statement__ = 18;
        lp_accum__.add(stan::math::lkj_corr_cholesky_lpdf<false>(L_Omega,
                         prior_omega));
        current_statement__ = 19;
        lp_accum__.add(stan::math::normal_lpdf<false>(
                         stan::math::to_vector(b), 0, prior_b));
        current_statement__ = 20;
        lp_accum__.add((stan::math::normal_lpdf<false>(sigma, 0, prior_sigma)
          -
          stan::math::normal_lccdf(stan::math::rep_vector(0, K), 0,
            prior_sigma)));
        current_statement__ = 21;
        lp_accum__.add(log_lik);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_hb_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,-1> z =
        Eigen::Matrix<double,-1,-1>::Constant(I, K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      z = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(I, K);
      Eigen::Matrix<double,-1,-1> b =
        Eigen::Matrix<double,-1,-1>::Constant(D, K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      b = in__.template read<Eigen::Matrix<local_scalar_t__,-1,-1>>(D, K);
      Eigen::Matrix<double,-1,-1> L_Omega =
        Eigen::Matrix<double,-1,-1>::Constant(K, K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      L_Omega = in__.template read_constrain_cholesky_factor_corr<
                  Eigen::Matrix<local_scalar_t__,-1,-1>, jacobian__>(lp__, K);
      Eigen::Matrix<double,-1,1> sigma =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      sigma = in__.template read_constrain_lb<
                Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, K);
      double log_lik = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,-1> raw =
        Eigen::Matrix<double,-1,-1>::Constant(I, K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> raw0 =
        Eigen::Matrix<double,-1,-1>::Constant(I, raw0_2dim__,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(z);
      out__.write(b);
      out__.write(L_Omega);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 5;
      log_lik = 0;
      current_statement__ = 10;
      stan::model::assign(raw,
        stan::math::add(stan::math::multiply(Z, b),
          stan::math::multiply(z,
            stan::math::transpose(
              stan::math::diag_pre_multiply(sigma, L_Omega)))),
        "assigning variable raw");
      current_statement__ = 11;
      stan::model::assign(raw0,
        stan::math::append_col(raw, stan::math::rep_vector(0, I)),
        "assigning variable raw0");
      current_statement__ = 14;
      for (int n = 1; n <= N; ++n) {
        current_statement__ = 12;
        log_lik = (log_lik +
          ((stan::model::rvalue(bw, "bw",
              stan::model::index_uni(
                stan::model::rvalue(y, "y", stan::model::index_uni(n))))
          *
          stan::model::rvalue(raw0, "raw0",
            stan::model::index_uni(
              stan::model::rvalue(id, "id", stan::model::index_uni(n))),
            stan::model::index_uni(
              stan::model::rvalue(item, "item",
                stan::model::index_uni(
                  stan::model::rvalue(y, "y", stan::model::index_uni(n)))))))
          -
          stan::math::log_sum_exp(
            stan::math::multiply(
              stan::model::rvalue(bw, "bw",
                stan::model::index_uni(
                  stan::model::rvalue(y, "y", stan::model::index_uni(n)))),
              stan::model::rvalue(raw0, "raw0",
                stan::model::index_uni(
                  stan::model::rvalue(id, "id", stan::model::index_uni(n))),
                stan::model::index_multi(
                  stan::model::rvalue(item, "item",
                    stan::model::index_min_max(
                      stan::model::rvalue(start_n, "start_n",
                        stan::model::index_uni(n)),
                      stan::model::rvalue(end_n, "end_n",
                        stan::model::index_uni(n))))))))));
      }
      current_statement__ = 5;
      stan::math::check_less_or_equal(function__, "log_lik", log_lik, 0);
      if (emit_transformed_parameters__) {
        out__.write(log_lik);
        out__.write(raw);
        out__.write(raw0);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,-1> Omega =
        Eigen::Matrix<double,-1,-1>::Constant(K, K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,-1> beta =
        Eigen::Matrix<double,-1,-1>::Constant(I, beta_2dim__,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 15;
      stan::model::assign(beta,
        stan::math::append_col(stan::math::append_col(orig_id, raw),
          stan::math::rep_vector(0, I)), "assigning variable beta");
      current_statement__ = 16;
      stan::model::assign(Omega,
        stan::math::multiply_lower_tri_self_transpose(L_Omega),
        "assigning variable Omega");
      out__.write(Omega);
      out__.write(beta);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(I, K, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(z,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(I, K),
        "assigning variable z");
      out__.write(z);
      Eigen::Matrix<local_scalar_t__,-1,-1> b =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, K, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(b,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(D, K),
        "assigning variable b");
      out__.write(b);
      Eigen::Matrix<local_scalar_t__,-1,-1> L_Omega =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, K, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(L_Omega,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,-1>>(K, K),
        "assigning variable L_Omega");
      out__.write_free_cholesky_factor_corr(L_Omega);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(sigma,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable sigma");
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "z", "double",
        std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(K)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "b", "double",
        std::vector<size_t>{static_cast<size_t>(D), static_cast<size_t>(K)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "L_Omega",
        "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(K)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,-1> z =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(I, K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> z_flat__;
        current_statement__ = 1;
        z_flat__ = context__.vals_r("z");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 1;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 1;
            stan::model::assign(z, z_flat__[(pos__ - 1)],
              "assigning variable z", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 1;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(z);
      Eigen::Matrix<local_scalar_t__,-1,-1> b =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(D, K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> b_flat__;
        current_statement__ = 2;
        b_flat__ = context__.vals_r("b");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 2;
          for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
            current_statement__ = 2;
            stan::model::assign(b, b_flat__[(pos__ - 1)],
              "assigning variable b", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 2;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(b);
      Eigen::Matrix<local_scalar_t__,-1,-1> L_Omega =
        Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> L_Omega_flat__;
        current_statement__ = 3;
        L_Omega_flat__ = context__.vals_r("L_Omega");
        current_statement__ = 3;
        pos__ = 1;
        current_statement__ = 3;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 3;
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            current_statement__ = 3;
            stan::model::assign(L_Omega, L_Omega_flat__[(pos__ - 1)],
              "assigning variable L_Omega", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 3;
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write_free_cholesky_factor_corr(L_Omega);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma_flat__;
        current_statement__ = 4;
        sigma_flat__ = context__.vals_r("sigma");
        current_statement__ = 4;
        pos__ = 1;
        current_statement__ = 4;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 4;
          stan::model::assign(sigma, sigma_flat__[(pos__ - 1)],
            "assigning variable sigma", stan::model::index_uni(sym1__));
          current_statement__ = 4;
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"z", "b", "L_Omega", "sigma"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"log_lik", "raw", "raw0"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"Omega", "beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(I),
                                                 static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(D),
                  static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K),
                  static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(I),
               static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(I),
               static_cast<size_t>(raw0_2dim__)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(K),
               static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(I),
               static_cast<size_t>(beta_2dim__)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
        param_names__.emplace_back(std::string() + "z" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
        param_names__.emplace_back(std::string() + "b" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "L_Omega" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          param_names__.emplace_back(std::string() + "raw" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= raw0_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          param_names__.emplace_back(std::string() + "raw0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          param_names__.emplace_back(std::string() + "Omega" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= beta_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
        param_names__.emplace_back(std::string() + "z" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= D; ++sym2__) {
        param_names__.emplace_back(std::string() + "b" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= ((K * (K - 1)) / 2); ++sym1__) {
      param_names__.emplace_back(std::string() + "L_Omega" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "log_lik");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          param_names__.emplace_back(std::string() + "raw" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= raw0_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          param_names__.emplace_back(std::string() + "raw0" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          param_names__.emplace_back(std::string() + "Omega" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
      for (int sym1__ = 1; sym1__ <= beta_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          param_names__.emplace_back(std::string() + "beta" + '.' +
            std::to_string(sym2__) + '.' + std::to_string(sym1__));
        }
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"z\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"L_Omega\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"raw0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(raw0_2dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Omega\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(beta_2dim__) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"z\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"b\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(D) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"L_Omega\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(((K * (K - 1)) /2)) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"raw\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"raw0\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(raw0_2dim__) + "},\"block\":\"transformed_parameters\"},{\"name\":\"Omega\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(K) + ",\"cols\":" + std::to_string(K) + "},\"block\":\"generated_quantities\"},{\"name\":\"beta\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(beta_2dim__) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((I * K) + (D * K)) + (K * K)) + K);
    const size_t num_transformed = emit_transformed_parameters * (((1 + (I *
      K)) + (I * raw0_2dim__)));
    const size_t num_gen_quantities = emit_generated_quantities * (((K * K) +
      (I * beta_2dim__)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((I * K) + (D * K)) + (K * K)) + K);
    const size_t num_transformed = emit_transformed_parameters * (((1 + (I *
      K)) + (I * raw0_2dim__)));
    const size_t num_gen_quantities = emit_generated_quantities * (((K * K) +
      (I * beta_2dim__)));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_hb_namespace::model_hb;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_hb_namespace::profiles__;
}
#endif
#endif
